EX01. Carregar “data” i "target" del conjunt de dades, i visualitza els 10 primers registres de cadascun.

In [1]:
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data
target = iris.target

print('\nDATA')
print('----')
print(data[:10])
print('\nTARGET')
print('------')
print(str(target[:10])+'\n')



DATA
----
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

TARGET
------
[0 0 0 0 0 0 0 0 0 0]



EX02. Concatena “data” i “target” en un nou array. Mostra els 5 primers registres.

In [2]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data
target = iris.target.reshape(150, 1)
data_target = np.concatenate((data, target), axis=1)

print('\ndata_target')
print('-----------')
print('')
print(data_target[:5])
print('')


data_target
-----------

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]



EX03. Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.

In [4]:
import numpy as np

from sklearn.datasets import load_iris
iris = load_iris()

long_sepals = iris.data[:,0]
mitja_long_sepals = np.around(np.mean(long_sepals), 2)
desv_long_sepals = np.around(np.std(long_sepals), 2)

print("\nMitjana longitud sèpals: "+str(mitja_long_sepals))
print("Desviació estàndard: "+str(desv_long_sepals)+'\n')

long_petals = iris.data[:,2]
mitja_long_petals = np.around(np.mean(long_petals), 2)
desv_long_petals = np.around(np.std(long_petals), 2)

print("Mitjana longitud pètals: "+str(mitja_long_petals))
print("Desviació estàndard: "+str(desv_long_petals)+'\n')


Mitjana longitud sèpals: 5.84
Desviació estàndard: 0.83

Mitjana longitud pètals: 3.76
Desviació estàndard: 1.76



EX04. Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.

In [6]:
import numpy as np
from numpy import random
from sklearn.datasets import load_iris

iris = load_iris()
long_sepals = iris.data[:,0]
long_petals = iris.data[:,2]

mostra_long_sepals = random.choice(long_sepals, size=(20))
mostra_long_petals = random.choice(long_petals, size=(20))

print("\nMostra longitud sèpals (20)")
print('---------------------------')
print(str(mostra_long_sepals))
print("\nMostra longitud pètals (20)")
print('---------------------------')
print(str(mostra_long_petals)+'\n')


Mostra longitud sèpals (20)
---------------------------
[6.  4.7 5.7 6.3 5.7 5.8 5.2 5.4 6.1 4.4 6.4 4.9 5.8 5.8 6.1 5.6 7.6 5.5
 6.7 4.4]

Mostra longitud pètals (20)
---------------------------
[4.7 1.6 5.6 5.1 4.5 4.2 4.8 4.5 4.5 6.4 5.  4.9 4.3 5.  1.5 4.7 5.1 4.7
 4.5 1.2]



EX05. Crea una matriu que mostri:

• La mitjana de cada característica per espècie.

• La desviació estàndard de cada característica per espècie.

In [8]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data
x = 0
y = 0

mitges = np.zeros((3, 4))

while x < 3:
    while y < 4:
        mitges[x, y] = round(np.mean(data[(x*50):(x*50+50), y]), 2)
        y += 1
    x += 1
    y = 0

print("\nMitjana (per característica i espècie)\n")
print(mitges, end = '\n\n')

x = 0
y = 0

desv = np.zeros((3, 4))

while x < 3:
    while y < 4:
        desv[x, y] = np.round(np.std(data[(x*50):(x*50+50), y]), 2)
        y += 1
    x += 1
    y = 0


print("Desviacions típiques (idem)\n")
print(str(desv)+'\n')


Mitjana (per característica i espècie)

[[5.01 3.43 1.46 0.25]
 [5.94 2.77 4.26 1.33]
 [6.59 2.97 5.55 2.03]]

Desviacions típiques (idem)

[[0.35 0.38 0.17 0.1 ]
 [0.51 0.31 0.47 0.2 ]
 [0.63 0.32 0.55 0.27]]



EX06.

• Calcula la quantitat de mostres per espècie.
• Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"



In [9]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data
especies = iris.target
noms = iris.target_names

tipus, mostra = np.unique(especies, return_counts = True)

x = 0

print("\nTamany de les mostres")
print("---------------------")
while x < 3:
    print(noms[x].capitalize()+': '+str(mostra[x]))
    x += 1
print('')

#Troba l'espècie amb el valor màxim mitjana de la variable "sèpal length (cm)"

x = 0
v_max = 0
x_max = 0
mitges_sepals = np.empty(3)

while x < 3:
    mitges_sepals[x] = np.round(np.mean(data[:(50+50*x), 0]), 2)
    if mitges_sepals[x] > v_max:
        v_max = mitges_sepals[x]
        x_max = x
    x += 1

print('Espècie mitjana longitud sèpals màxima')
print('--------------------------------------')
print(str(noms[x_max].capitalize())+': '+str(v_max)+'\n')



Tamany de les mostres
---------------------
Setosa: 50
Versicolor: 50
Virginica: 50

Espècie mitjana longitud sèpals màxima
--------------------------------------
Virginica: 5.84



EX07.

• Calcula la matriu de correlació entre les variables.

• Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho.

• Troba la mostra amb els pètals més grans.

In [10]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data

# 7.1. Calcula la matriu de correlació entre les variables.

data_transpuesta = np.transpose(data)
print('\n7.1 Matriu de correlacions entre les 4 característiques:\n')
print(np.corrcoef(data_transpuesta))

# 7.2. Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho.

mitja = np.round(np.mean(data[:,2]), 3)

# Valors majors a la mitjana

majors_mitja = np.array([])

for x in data:
    if (x[2] > mitja):
        majors_mitja = np.append(majors_mitja, x[2])

# Impressió valors

print('\n7.2 Pètals més llargs que la mitjana')
print('\nMitjana: '+str(mitja)+' cm.')
print('\nValors més grans:\n\n'+str(majors_mitja)+'\n')

# 7.3. Troba la mostra amb els pètals més grans.

major_petal = np.amax(majors_mitja)
print('7.3 Pètal més llarg de tots: '+str(major_petal)+' cm.\n')


7.1 Matriu de correlacions entre les 4 característiques:

[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]

7.2 Pètals més llargs que la mitjana

Mitjana: 3.758 cm.

Valors més grans:

[4.7 4.5 4.9 4.  4.6 4.5 4.7 4.6 3.9 4.2 4.  4.7 4.4 4.5 4.1 4.5 3.9 4.8
 4.  4.9 4.7 4.3 4.4 4.8 5.  4.5 3.8 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.  4.4
 4.6 4.  4.2 4.2 4.2 4.3 4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3 5.8 6.1 5.1
 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.  4.8 4.9 5.6
 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9 5.7 5.2 5.
 5.2 5.4 5.1]

7.3 Pètal més llarg de tots: 6.9 cm.



EX08. Troba l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals.

In [11]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data

# 8. Espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals.

mitjana_sepals = np.array([])
mitjana_petals = np.array([])
x = 0

# Un array para sépalos (con los tres tipos de flores) y otro para pétalos

while (x < 3):
    mitjana_sepals = np.append(mitjana_sepals, np.mean(data[50*x:(50+50*x),0]))
    mitjana_petals = np.append(mitjana_petals, np.mean(data[50*x:(50+50*x),2]))
    x += 1

# Cálculo de las diferencias

y = 0
val_max = 0
diferencia = mitjana_sepals - mitjana_petals

while (y<3):
    if diferencia[y] > val_max:
        val_max = diferencia[y]
        especie = iris.target_names[y]
    y += 1

print('\n8. Diferència màxima entre longitud de sèpals i pètals\n')
print(especie.capitalize()+': '+str(val_max)+' cm.\n')


8. Diferència màxima entre longitud de sèpals i pètals

Setosa: 3.544 cm.

